### ISSUE TITLE
How does this plugin work?

### ISSUE THREAD

**Issue by noib3** [mrjones2014/dash.nvim#130]
Hi there, I have a totally selfish request. I just started writing a [completion framework](https://github.com/noib3/nvim-compleet) for Neovim in Rust, and I was wondering if you could talk about the approach you took w/ this plugin.

Reading the little documentation I could find online, I was under the impression that all neovim plugins not written in Vimscript/Lua run out of process and communicated w/ neovim using something like rpc channels, w/ `vim.rpcrequest` or `vim.rpcnotify`. This is also what I've been doing w/ my plugin up to now.

I assume you're using a different approach since you don't depend on the `nvim-rs` crate which is needed to interface w/ neovim via rpc, is that correct?

I asked myself if there was a way to talk to the underlying nvim C code directly from Rust via ffi, without even touching Lua or sending messages back and forth with rpc. I would imagine a lot of IO overhead could be avoided that way. Is that what you're doing?

Thanks, and feel free to close this if it's out of topic.

**Comment by mrjones2014** [comment]
off topic for the repo but feel free to send me a DM on telegram t.me/mones44

**Comment by mrjones2014** [comment]
for future viewers: https://mjones.network/how-to-write-neovim-plugins-in-rust
