### ISSUE TITLE
file_type_keywords not being detected

### ISSUE THREAD

**Issue by Tseyang** [mrjones2014/dash.nvim#136]
First off, thank you for this plugin! Saves me a ton of effort having to switch windows etc.

I had a question around configuration: I'm not able to get the `file_type_keywords` to be picked up by the plugin, even though the other configuration settings I added are detected.

I'm using Telescope with:

```lua
require('telescope').setup({
  defaults = {
    -- Default configuration for telescope goes here:
    -- config_key = value,
    mappings = {
      i = {
        -- map actions.which_key to <C-h> (default: <C-/>)
        -- actions.which_key shows the mappings for your picker,
        -- e.g. git_{create, delete, ...}_branch for the git_branches picker
        ["<C-h>"] = "which_key"
      }
    },
    buffer_previewer_maker = new_maker,
  },
  pickers = {
    -- Default configuration for builtin pickers goes here:
    -- picker_name = {
    --   picker_config_key = value,
    --   ...
    -- }
    -- Now the picker_config_key will be applied every time you call this
    -- builtin picker
  },
  extensions = {
    -- Your extension configuration goes here:
    -- extension_name = {
    --   extension_config_key = value,
    -- }
    -- please take a look at the readme of the extension you want to configure
    dash = {
      search_engine = 'google',
      file_type_keywords = {
        ruby = { 'ruby', 'rails' },  -- this doesn't seem to be working
        javascript = { 'javascript', 'nodejs' },
        typescript = { 'typescript', 'javascript', 'nodejs' },
        typescriptreact = { 'typescript', 'javascript', 'react' },
        javascriptreact = { 'javascript', 'react' },
      }
    }
  }
})
```

The `search_engine` configuration is being detected, but the `file_type_keywords` one isn't. I'm sure there's some misconfiguration by me going on but have not been able to determine what it is. I'm hoping I can get some help figuring out how to set this up properly.

Thank you again for this plugin!

**Comment by Tseyang** [comment]
Hey, yea I have the docsets:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/20376539/164284900-e3bb608e-3011-43c2-a94e-d6c7a9f78778.png">


<img width="708" alt="image" src="https://user-images.githubusercontent.com/20376539/164284981-4859b6dc-4531-4280-89f5-c29d3e9a4f2c.png">

**Comment by mrjones2014** [comment]
Hmm... Interesting. I'm unable to reproduce.

**Comment by Tseyang** [comment]
is there a way to debug this? I'm willing to mess around with building the binary. My last resort was going to be adding to the `.rs` config directly.

**Comment by Tseyang** [comment]
No, I'm using `vim-plug`. The issue occurs with `:Dash`, but with `:Telescope dash search`, it shows the search engine configuration, but no filters are applied (not even the `ruby`-only).

**Comment by mrjones2014** [comment]
Gotcha. I'm not sure how to debug it really, since I can't reproduce the issue.

**Comment by Tseyang** [comment]
Turns out I needed to specify the `dash_app_path` explicitly. I should've tested that earlier. Once I set `dash_app_path = '/Applications/Dash.app',` it  started working.

Thank you for this plugin + the responses!

**Comment by mrjones2014** [comment]
Huh, that seems weird, but glad you got it working!
