### ISSUE TITLE
FZF/fzf-lua support (or generic datasource provider for other pickers)

### ISSUE THREAD

**Issue by megalithic** [mrjones2014/dash.nvim#25]
Love this! I imagine that since you don't use fzf-lua you'd likely not want to spend time adding support. I haven't dove deep into this repo yet, so forgive me if this already exists.. would you be willing to add some sort of provider so that other pickers might be used?

Thanks!

(PS. I'd be interested in adding fzf-lua support if you were up for having that added)

**Comment by mrjones2014** [comment]
I've not used fzf-lua but I'm open to adding support for it. I would gladly merge a PR if you submit one!

**Comment by mrjones2014** [comment]
@megalithic  also, you can get the path to the rust backend binary via `vim.g.dash_root_dir .. require('dash.constants').dash_nvim_bin_path`, and the path to Dash.app is in config, `require('dash.utils.config').config.dash_app_path`.

**Comment by mrjones2014** [comment]
> also, documenting this added benefit of being able to call the rust binary directly and build your own provider code?

ah, yeah, on second thought, maybe we shouldn't _require_ either, and instead just offer the full path to the Rust binary as a constant added to `dash.constants` module.

**Comment by mrjones2014** [comment]
@megalithic any timeline on getting a PR together for this? It would be cool to decouple this from telescope so we can reach more users.

if you don’t have time I might start taking a whack at this.

**Comment by mrjones2014** [comment]
I've got a rough start here but idk what I'm doing really with fzf-lua's API 

https://github.com/mrjones2014/dash.nvim/tree/matjones/25-fzf-lua-support

**Comment by mrjones2014** [comment]
@megalithic fzf-lua is now supported! 😄
