### ISSUE TITLE
Feature Request: Docs for word under cursor

### ISSUE THREAD

**Issue by bmulholland** [mrjones2014/dash.nvim#26]
I'm coming from [dash.vim](https://raw.githubusercontent.com/rizzatti/dash.vim), which has a feature to search for the word under the cursor. (Optionally?) Having the telescope window auto-populate with that word would be helpful.

However, I found that this didn't always work as well as one would like, because the method searched could sometimes belong to quite a few different types of classes. For example, `open` in Ruby, which in Dash gives results for 36 objects. So my _dream_ feature would be to use the LSP and/or Treesitter to lookup the docs for the method on the correct object type. In other words, `var_that_is_a_tempfile.[o]pen` (with the cursor on the o) would open the docs for specifically Tempfile.open.

**Comment by mrjones2014** [comment]
Possibly related: #25
